import type { ExportTemplateRenderData } from "./index";

export function renderClinicalSummaryTemplate(data: ExportTemplateRenderData): string {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Clinical Summary</title>
    <style>${styles()}</style>
  </head>
  <body class="w-[1080px] h-[1350px] bg-stone-100 text-stone-900">
    <main class="h-full p-14 flex flex-col gap-6">
      <header class="header">
        <h1 class="title">Clinical Summary</h1>
        <span class="pill">${escapeHtml(data.platform.toUpperCase())}</span>
      </header>
      <section class="card">
        <h2 class="subtitle">Post Content</h2>
        <p class="body">${escapeHtml(data.contentText)}</p>
      </section>
      <section class="card">
        <h2 class="subtitle">Evidence Notes</h2>
        <p class="body">${escapeHtml(data.citationSummary)}</p>
      </section>
      <footer class="footer">
        Generated by CiteCreate Engine
      </footer>
    </main>
  </body>
</html>`;
}

function styles(): string {
  return `
* { box-sizing: border-box; }
body { margin:0; font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, sans-serif; }
.w-\\[1080px\\] { width:1080px; }
.h-\\[1350px\\] { height:1350px; }
.h-full { height:100%; }
.p-14 { padding:3.5rem; }
.flex { display:flex; }
.flex-col { flex-direction:column; }
.gap-6 { gap:1.5rem; }
.bg-stone-100 { background:#f5f5f4; }
.text-stone-900 { color:#1c1917; }
.header { display:flex; justify-content:space-between; align-items:center; }
.title { margin:0; font-size:3rem; letter-spacing:.02em; }
.pill { background:#1c1917; color:#fafaf9; padding:.5rem .9rem; border-radius:999px; font-size:.75rem; letter-spacing:.08em; text-transform:uppercase; }
.card { background:#fff; border:1px solid #d6d3d1; border-radius:18px; padding:1.8rem; display:flex; flex-direction:column; gap:.9rem; }
.subtitle { margin:0; font-size:1.2rem; text-transform:uppercase; letter-spacing:.07em; color:#44403c; }
.body { margin:0; font-size:1.3rem; line-height:1.6; }
.footer { margin-top:auto; color:#57534e; font-size:.95rem; letter-spacing:.02em; }
`;
}

function escapeHtml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}
